import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { WalletProvider } from "@/context/WalletContext";
import Footer from "@/components/Footer";
import { EdgeStoreProvider } from "@/components/EdgeStoreProvider";
import { AppProvider } from "@/src/context/AppContext";

interface EthereumProvider {
  isMetaMask?: boolean;
  isStatus?: boolean;
  host?: string;
  path?: string;
  sendAsync?: (
    request: { method: string; params?: Array<any> },
    callback: (error: any, response: any) => void
  ) => void;
  send?: (
    request: { method: string; params?: Array<any> },
    callback: (error: any, response: any) => void
  ) => void;
  request: (request: { method: string; params?: Array<any> }) => Promise<any>;
  on: (method: string, listener: (...args: any[]) => void) => void;
  removeListener: (method: string, listener: (...args: any[]) => void) => void;
}

declare global {
  interface Window {
    ethereum: EthereumProvider;
  }
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EdgeStoreProvider>
        <WalletProvider>
          <AppProvider>
          <Navbar />
          {children}
          <Footer />
          </AppProvider>
        </WalletProvider>
        </EdgeStoreProvider>

      </body>
    </html>
  );
}
